register:
  path: /register
  controller: App\Controller\UserController::register

confirm:
  path: /confirm/{token}
  controller: App\Controller\UserController::confirm

password:
  path: /password
  controller: App\Controller\UserController::password

reset:
  path: /password/reset
  controller: App\Controller\UserController::resetPassword

change_password:
  path: /password/change
  controller: App\Controller\UserController::recoverPassword