index:
    path: /
    controller: App\Controller\HomeController::index

event:
    resource: 'routes/event.yaml'
    prefix: '/event'

talk:
    resource: 'routes/talk.yaml'
    prefix: '/talk'

tag:
    resource: 'routes/tag.yaml'
    prefix: '/tag'