index:
    path: /
    controller: App\Controller\HomeController::index

event:
    resource: routes/event.yaml
    prefix: /event

talk:
    resource: routes/talk.yaml
    prefix: /talk

tag:
    resource: routes/tag.yaml
    prefix: /tag

user:
    resource: routes/user.yaml
    prefix: /user

rate:
    resource: routes/rate.yaml
    prefix: /rate

# Connexions

login:
    path: /login
    controller: App\Controller\UserController::login

logout:
    path: /logout
    controller: App\Controller\UserController::logout

account:
    resource: routes/account.yaml
    prefix: /account